version: "3.8"

services:
    # AI-Agent:
    #     build:
    #         context: ./AI-Agent
    #         dockerfile: Dockerfile
    #     ports:
    #         - "5000:5000"
    #     environment:
    #         - OPENAI_API_KEY=${OPENAI_API_KEY}
    #         - TAVILY_API_KEY=${TAVILY_API_KEY}
    #         - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "0.0.0.0:5173:5173"
        volumes:
            - ./frontend:/app
        environment:
            - REACT_APP_API_URL=${BACKEND_URL:-http://localhost:8080}
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "0.0.0.0:8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=${DB_URL:-jdbc:postgresql://host.docker.internal:5432/monkey_d_vuvi}
            - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-admin}
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-admin}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        ports:
            - "0.0.0.0:6001:6001"
        environment:
            - POSTGRES_DB=${DB_NAME:-monkey_d_vuvi}
            - POSTGRES_USER=${DB_USERNAME:-admin}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-admin}
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
