version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./frontend:/app
        environment:
            - REACT_APP_API_URL=http://localhost:8080
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=${DB_URL:-jdbc:postgresql://host.docker.internal:5432/monkey_d_vuvi}
            - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-admin}
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-admin}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${DB_NAME:-monkey_d_vuvi}
            - POSTGRES_USER=${DB_USERNAME:-admin}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-admin}
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
