services:
    # Backend Service
    - type: web
      name: monkey-d-vuvi-backend
      env: docker
      dockerfilePath: Dockerfile
      rootDir: backend
      plan: free
      envVars:
          - key: SPRING_DATASOURCE_URL
            value: ${DB_URL}
          - key: SPRING_DATASOURCE_USERNAME
            value: ${DB_USERNAME}
          - key: SPRING_DATASOURCE_PASSWORD
            value: ${DB_PASSWORD}
          - key: CORS_ALLOWED_ORIGINS
            value: https://monkey-d-vuvi-frontend.onrender.com
      healthCheckPath: /actuator/health

    # Frontend Service
    - type: web
      name: monkey-d-vuvi-frontend
      env: docker
      dockerfilePath: Dockerfile.prod
      rootDir: frontend
      plan: free
      envVars:
          - key: PORT
            value: 80
          - key: VITE_BACKEND_HOST
            value: monkey-d-vuvi-backend.onrender.com
          - key: VITE_BACKEND_PORT
            value: 443
          - key: SERVER_NAME
            value: monkey-d-vuvi-frontend.onrender.com
          - key: CORS_ALLOWED_ORIGIN
            value: https://monkey-d-vuvi-frontend.onrender.com
          - key: NODE_ENV
            value: production
