services:
    # Backend Service
    - type: web
      name: monkey-d-vuvi-backend
      env: docker
      dockerfilePath: ./backend/Dockerfile
      plan: free
      envVars:
          - key: SPRING_DATASOURCE_URL
            value: ${DB_URL}
          - key: SPRING_DATASOURCE_USERNAME
            value: ${DB_USERNAME}
          - key: SPRING_DATASOURCE_PASSWORD
            value: ${DB_PASSWORD}
      healthCheckPath: /actuator/health

    # Frontend Service
    - type: web
      name: monkey-d-vuvi-frontend
      env: docker
      dockerfilePath: ./frontend/Dockerfile
      plan: free
      envVars:
          - key: REACT_APP_API_URL
            value: https://monkey-d-vuvi-backend.onrender.com
